repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.1.0
  hooks:
    - id: commitizen
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.10.0
  hooks:
    - id: black-jupyter
      files: \.ipynb$
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
      files: \.ipynb$